# Default values for elk-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag:
    init: busybox:1.27.2
    elasticsearch: quay.io/pires/docker-elasticsearch-kubernetes:6.4.2
    logstash: docker.elastic.co/logstash/logstash:6.4.2
    kibana: docker.elastic.co/kibana/kibana-oss:6.4.2
    beats:
      packetbeats: docker.elastic.co/beats/packetbeat:6.4.2
      filebeats: docker.elastic.co/beats/filebeat:6.4.2
  pullPolicy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

pod:
  replicas:
    master: 3
    data: 3
    ingest: 3
  resources:
    enabled: true
    unit:
      memory: "Gi"
      cpu: "m"
    master:
      requests:
        memory: "1"
        cpu: "100"
      limits:
        memory: "1"
        cpu: "2000"
    data:
      requests:
        memory: "4"
        cpu: "100"
      limits:
        memory: "4"
        cpu: "2000"
    ingest:
      requests:
        memory: "2"
        cpu: "100"
      limits:
        memory: "2"
        cpu: "2000"

conf:
  init:
    max_map_count: 262144
  cluster:
    name: myesdb
  elasticsearch:
    env:
      data:
        java_opts: -Xms2g -Xmx2g
      master:
        java_opts: -Xms256m -Xmx256m
      ingest:
        java_opts: -Xms1g -Xmx1g
  kibana:
  #Recommend running Kibana separate from your Elasticsearch 'data' or 'master' nodes
    config_map:
      elasticsearch_url: http://elasticsearch:9200
      elasticsearch_master_url: http://elasticsearch-master:9200

storage:
  enabled: true
  pvc:
    name: pvc-elastic
    access_mode: [ "ReadWriteOnce" ]
  requests:
    storage:
      master: 5Gi
      data: 10Gi
  storage_class: gluster

endpoints:
  elasticsearch:
    port:
      client:
        default: 9200
      http:
        default: 80
      discovery:
        default: 9300
  kibana:
    port:
      ui:
        default: 5601
      nodeport:
        default: 30003
      http:
        default: 80
  logstash:
    port:
      tcp:
        default: 12345
      nodeport:
        default: 30002

manifests:
  statfulset_data: true
  statfulset_master: false
  deployment_master: true
  deployment_ingest: true
  deployment_kibana: true
  deployment_logstash: true
  deployment_kibana_kubeproxy: true
  config_kibana: true
  config_kibana_master: true
  kibana_service: true
  master_service: true
  ingest_service: true
  data_service: true
  kibana_kubeproxy_service: true