# Default values for elk-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag:
    init: busybox:1.27.2
    elasticsearch: quay.io/pires/docker-elasticsearch-kubernetes:6.4.2
    logstash: docker.elastic.co/logstash/logstash:6.4.2
    kibana: docker.elastic.co/kibana/kibana-oss:6.4.2
    beats:
      packetbeats: docker.elastic.co/beats/packetbeat:6.4.2
      filebeats: docker.elastic.co/beats/filebeat:6.4.2
  pullPolicy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

pod:
  replicas:
    master: 3
    data: 3
    ingest: 3
  resources:
    enabled: true
    master:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    data:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    ingest:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

conf:
  init:
    max_map_count: 262144
  cluster:
    name: myesdb
  elasticsearch:
    env:
      data:
      master:
      ingest:
  kibana:
    config_map:
      elasticsearch_url: http://elasticsearch:9200

storage:
  enabled: true
  pvc:
    name: pvc-elastic
    access_mode: [ "ReadWriteOnce" ]
  requests:
    storage:
      master: 5Gi
      data: 10Gi
  storage_class: gluster

endpoints:
  elasticsearch:
    port:
      client:
        default: 9200
      http:
        default: 80
      discovery:
        default: 9300
  kibana:
    port:
      ui:
        default: 5601
      nodeport:
        default: 30003

manifests:
  deployment_master: true
  statfulset_data: true
  statfulset_master: false
  deployment_ingest: true
  deployment_kibana: true
  config_kibana: true
  kibana_service: true
  master_service: true
  ingest_service: true
  data_service: true
