apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: {{ .Values.endpoints.namespace }}
data:
  elasticsearch.yml: |
{{ tuple "bin/_elasticsearch.yml.tpl" . | include "tools.template" | indent 4 }}
{{- if eq .Values.conf.elasticsearch.disable_xpack true }}
{{ "xpack.ml.enabled: false" | indent 4 }}
{{ end }}
  docker-entrypoint.sh: |
{{ tuple "bin/_docker-entrypoint.sh.tpl" . | include "tools.template" | indent 4 }}