apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: {{ .Values.endpoints.namespace }}
data:
  logstash.yml: |
{{ tuple "bin/_logstash.yml.tpl" . | include "tools.template" | indent 4 }}