{{- if .Values.manifests.config_kibana }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: {{ .Values.endpoints.namespace }}
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.host: "0"
    elasticsearch.url: {{.Values.conf.kibana.config_map.elasticsearch_url}}
{{ end }}