{{- if .Values.manifests.deployment_logstash }}
{{- $serviceAccountName := "elasticsearch-logstash"}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: {{ .Values.endpoints.namespace }}
  labels:
    component: elasticsearch
    role: logstash
spec:
  serviceName: {{ $serviceAccountName }}
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: logstash
    spec:
      containers:
      - name: logstash
        image: {{ .Values.image.tag.logstash }}
        # env:
        # resources:
        #   limits:
        #     cpu: 1000m
        #   requests:
        #     cpu: 100m
        ports:
        - containerPort: {{ tuple "logstash" "internal" "tcp" . | include "endpoint_port_lookup" }}
          name: http
          protocol: TCP
        volumeMounts:
          - name: pipline
            mountPath: /usr/share/logstash/pipeline
            readOnly: true
          - name: patterns
            mountPath: /usr/share/logstash/patterns
            readOnly: true
          - name: config
            subPath: logstash.yml
            mountPath: /usr/share/logstash/config/logstash.yml
            readOnly: true
      volumes:
        - name: pipline
          configMap:
            name: logstash-pipline
        - name: config
          configMap:
            name: logstash-config
        - name: patterns
          configMap:
            name: logstash-patterns
{{ end }}