{{- if .Values.manifests.deployment_master }}
{{- $serviceAccountName := "elasticsearch-master"}}

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  serviceName: {{ $serviceAccountName }}
  replicas: {{ .Values.pod.replicas.master }}
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: {{ .Values.image.tag.init }}
        command:
        - sysctl
        - -w
        - vm.max_map_count={{ .Values.conf.init.max_map_count }}
        securityContext:
          privileged: true
      containers:
      - name: es-master
        image: {{ .Values.image.tag.elasticsearch }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: {{ .Values.conf.cluster.name }}
        - name: NUMBER_OF_MASTERS
          value: {{ div .Values.pod.replicas.master 2 | add 1 | quote}}
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        # - name: HTTP_ENABLE
        #   value: "false"
        - name: ES_JAVA_OPTS
          value: {{ .Values.conf.elasticsearch.env.master.java_opts }}
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
{{ tuple . .Values.pod.resources.master | include "kubernetes_resources" | indent 8 }}
        ports:
        - containerPort: {{ tuple "elasticsearch" "internal" "discovery" . | include "endpoint_port_lookup" }}
          name: transport
        - containerPort: {{ tuple "elasticsearch" "internal" "client" . | include "endpoint_port_lookup" }}
          name: http
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_cluster/health
        #     port: http
        #   initialDelaySeconds: 20
        #   timeoutSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
{{ end }}