{{- if .Values.manifests.data_service }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  labels:
    component: elasticsearch
    role: data
spec:
  ports:
  - port: {{ tuple "elasticsearch" "internal" "discovery" . | include "endpoint_port_lookup" }}
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: data
{{ end }}