{{- if .Values.manifests.ingest_service }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest-np
  namespace: {{ .Values.endpoints.namespace }}
  labels:
    component: elasticsearch
    role: ingest
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: http
    port: {{ tuple "elasticsearch" "internal" "client" . | include "endpoint_port_lookup" }}
    protocol: TCP
    targetPort: http
    {{- if eq .Values.endpoints.specific_nodeport true }}
    nodePort: {{ tuple "elasticsearch" "node_port" "ingest" . | include "endpoint_port_lookup" }}
    {{ end }}
{{ end }}