{{- if .Values.manifests.ingest_service }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest
  labels:
    component: elasticsearch
    role: ingest
spec:
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: http
    port: {{ tuple "elasticsearch" "internal" "client" . | include "endpoint_port_lookup" }}
{{ end }}