apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logstash
  labels:
    component: elasticsearch
    role: logstash
spec:
  type: NodePort
  ports:
  - port: {{ tuple "logstash" "internal" "tcp" . | include "endpoint_port_lookup" }}
    name: transport
  selector:
    component: elasticsearch
    role: logstash