apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elasticsearch
    role: master
spec:
  ports:
  - port: {{ tuple "elasticsearch" "internal" "discovery" . | include "endpoint_port_lookup" }}
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: master