apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: {{ .Values.endpoints.namespace }}
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: http
    port: {{ tuple "elasticsearch" "internal" "client" . | include "endpoint_port_lookup" }}
#type: LoadBalancer