{{- if .Values.manifests.kibana_kubeproxy_service }}
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.endpoints.namespace }}
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: {{ tuple "kibana" "internal" "http" . | include "endpoint_port_lookup" }}
    protocol: TCP
    targetPort: ui
{{ end }}