{{- if .Values.manifests.kibana_service }}
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  labels:
    component: kibana-logging
spec:
  selector:
    component: kibana-logging
  type: NodePort
  ports:
  - name: http
    port: {{ tuple "kibana" "internal" "ui" . | include "endpoint_port_lookup" }}
    {{- if eq .Values.endpoints.specific_nodeport true }}
    nodePort: {{ tuple "kibana" "node_port" "http" . | include "endpoint_port_lookup" }}
    {{ end }}
    protocol: TCP
    targetPort: ui
{{ end }}