{{- if .Values.manifests.statfulset_data }}
{{- $serviceAccountName := "elasticsearch-data"}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  serviceName: {{ $serviceAccountName }}
  replicas: {{ .Values.pod.replicas.data }}
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count={{ .Values.conf.init.max_map_count }}
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: {{ .Values.image.tag.elasticsearch }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: {{ .Values.conf.cluster.name }}
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: {{ .Values.pod.resources.data | include "es_java_opts" | quote }}
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
{{ tuple . .Values.pod.resources.data | include "kubernetes_resources" | indent 8 }}
        ports:
        - containerPort: {{ tuple "elasticsearch" "internal" "client" . | include "endpoint_port_lookup" }}
          name: http
        - containerPort: {{ tuple "elasticsearch" "internal" "discovery" . | include "endpoint_port_lookup" }}
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: {{ .Values.storage.storage_class }}
      accessModes: {{ .Values.storage.pvc.access_mode }}
      resources:
        requests:
          storage: {{ .Values.storage.requests.storage.data  }}
{{ end }}